export { buildPath, roundedUnion } from './core/path.js';
export { unionRects } from './core/union.js';
export { calculateFillets, filletsToPathString } from './core/fillet.js';
export { getCornerInfo, getFilletCenter, removeCollinear, ensureClockwise, polygonArea } from './core/geometry.js';
export { createSvgLayer, setPathD } from './render/svg.js';
export { setGradient } from './render/gradient.js';
export { snapValue, snapGeometry, createSnapManager } from './render/pixelSnap.js';
export { attach } from './dom/attach.js';
export { joinShapes } from './dom/joinShapes.js';
export { glue } from './dom/glue.js';
export { buildPatchesPath, resolvePatchColor } from './dom/patches.js';
export { easings, getEasing } from './anim/easing.js';
export { createScheduler, sharedScheduler } from './anim/scheduler.js';
export { animate, interpolateGeometry } from './anim/animate.js';
